services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: my_backend
    ports:
      - "10011:10011"
    networks:
      - my_backend_net

networks:
  my_backend_net:
    driver: bridge